name: tarazcheh
description: ترازچه - اپ ساده دخل و خرج
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.3.6
  drift: ^2.7.0
  drift_flutter: ^2.7.0
  sqlite3_flutter_libs: ^0.5.7
  path_provider: ^2.0.15
  intl: ^0.18.1
  uuid: ^3.1.0
  workmanager: ^0.5.0
  flutter_local_notifications: ^12.0.4
  notification_listener_service: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  drift_dev: ^2.7.0
